name: Build & Release to npm
on:
    push:
        tags:
          - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: 22.16.0
                registry-url: 'https://registry.npmjs.org'

            - name: Install requirements
              run: npm i

            - name: Build
              run: tsc

            - name: Publish
              run: npm publish --access public
              env: 
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}